# Generated by Django 5.1.4 on 2024-12-17 21:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Breve descripción del gasto.",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Comida"),
                            ("TRANSPORT", "Transporte"),
                            ("UTILITIES", "Servicios Públicos"),
                            ("ENTERTAINMENT", "Entretenimiento"),
                            ("OTHER", "Otros"),
                        ],
                        help_text="Categoría a la que pertenece el gasto.",
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto gastado. Debe ser mayor a cero.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha en que se realizó el gasto.",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
